config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :body
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many(:posts, dependent: :destroy)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_current_page, except: [:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :show_record_not_found

  # GET /posts
  # GET /posts.json
  def index
      @posts = Post.paginate(page: params[:page], :per_page => 10)
                   .order('title')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = User.find_by username: params[:username]

    respond_to do |format|
      if @post.save
        format.html { redirect_to(post_url(@post, page: @current_page),
                                  notice: 'Post was successful') }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to(post_url(@post, page: @current_page),
                                  notice: 'Post was successfully updated.') }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url(page: @current_page) }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def set_current_page
    @current_page = params[:page] || 1
  end

  def show_record_not_found(exception)
    respond_to do |format|
      format.html {
        redirect_to(posts_url(page: @current_page),
                    notice: 'Post no longer exists.')
      }
      format.json {
        render json: '{Post no longer exists.}',
               status: :unprocessable_entity
      }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_page, except: [:index]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :show_record_not_found

  # GET /users
  # GET /users.json
  def index
      @users = User.paginate(page: params[:page], :per_page => 10)
                   .order('lastname, firstname')
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to(user_url(@user, page: @current_page),
                                  notice: 'Account was successfully created.') }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to(user_url(@user, page: @current_page),
                                  notice: 'Account was successfully updated.') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url(page: @current_page) }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def set_current_page
    @current_page = params[:page] || 1
  end

  def show_record_not_found(exception)
    respond_to do |format|
      format.html {
        redirect_to(users_url(page: @current_page),
                    notice: 'Account no longer exists.')
      }
      format.json {
        render json: '{Account no longer exists.}',
               status: :unprocessable_entity
      }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:lastname, :firstname, :username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<pre>
  Hello world
</pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <div class="header">
      <%# <%= render :partial => 'sessions/login' %1> %>
      <div class="navigation">
        <%= render_navigation %>
      </div>

      <% flash.each do |key, value| %>
        <span class="flash_<%= key %>">
          <span class="flash_message"><%= value %></span>
        </span>
      <% end %>

    </div>
    <div class="content">
      <%= yield %>
    </div>

    <div id="footer">
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag 'username', 'Username' %><br>
    <%=
      if post.user
        text_field_tag 'username', post.user.username
      else
        text_field_tag 'username'
      end
    %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', post_path(@post, page: @current_page) %> |
<%= link_to 'Back', posts_path(page: @current_page) %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% if @posts.length > 0 %>
    <table>
      <thead>
      <tr>
        <th>User</th>
        <th>Title</th>
        <th>Body</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @posts.each do |post| %>
          <tr>
            <% if post.user %>
              <td><%= link_to(post.user.username, user_path(post.user)) %></td>
            <% else %>
              <td> Anonymous </td>
            <% end %>
            <td><%= post.title %></td>
            <td><%= post.body %></td>
            <td><%= link_to('Show', post_path(post, page: @posts.current_page)) %></td>
            <td><%= link_to('Edit', edit_post_path(post, page: @posts.current_page)) %></td>
            <td><%= link_to('Delete', post_path(post, page: @posts.current_page), data: {confirm: 'Are you sure?'}, method: :delete)
            %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>
<br>
<div class="digg_pagination">
  <div>
    <%= page_entries_info @posts %>
  </div>
  <%= will_paginate @posts, container: false %>
</div>
<br>

<%= link_to 'New post', new_post_path(page: @posts.current_page) %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path(page: @current_page) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <% if @post.user %>
    <td><%= link_to('Show', user_path(@post.user.username)) %></td>
  <% else %>
    <td> Anonymous </td>
  <% end %>
  <strong>Title:</strong>
  <%= @post.title %>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post, page: @current_page) %> |
<%= link_to 'Back', posts_path(page: @current_page) %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', user_path(@user, page: @current_page) %> |
<%= link_to 'Back', users_path(page: @current_page) %>

app/views/users/index.html.erb
<h1>User accounts</h1>

<% if @users.length > 0 %>
    <table>
      <thead>
      <tr>
        <th>Username</th>
        <th>Surname</th>
        <th>First name</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.username %></td>
            <td><%= user.lastname %></td>
            <td><%= user.firstname %></td>
            <td><%= link_to('Show', user_path(user, page: @users.current_page)) %></td>
            <td><%= link_to('Edit', edit_user_path(user, page: @users.current_page)) %></td>
            <td><%= link_to('Delete', user_path(user, page: @users.current_page), data: {confirm: 'Are you sure?'}, method: :delete)
            %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>
<br>
<div class="digg_pagination">
  <div>
    <%= page_entries_info @users %>
  </div>
  <%= will_paginate @users, container: false %>
</div>
<br>

<%= link_to 'New user', new_user_path(page: @users.current_page) %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path(page: @current_page) %>

app/views/users/show.html.erb
<h1>User details</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
    <%= @user.username %>
</p>

<p>
  <strong>Surname:</strong>
    <%= @user.lastname %>
</p>

<p>
  <strong>Firstname:</strong>
    <%= @user.firstname %>
</p>

<%= link_to 'Edit', edit_user_path(@user, page: @current_page) %> |
<%= link_to 'Back', users_path(page: @current_page) %>